ER-1214: Added empty select as default
eReolen/ereolen pull request #37
Opened 2021-10-29 12:27 UTC by martinyde

https://jira.itkdev.dk/browse/ER-1215

2021-10-29 13:20 UTC, cableman commented on ereolen_support/ereolen_support.helper.inc
> +  }
The list should be initialised before adding anything to it. So you can remove the else statement

```php
$list = [];
if ($add_select) {
    $list['_none'] = t('- Select -');
  }
```

2021-10-29 13:21 UTC, cableman requested changes
Minor change

2021-10-29 18:36 UTC, martinyde commented on ereolen_support/ereolen_support.helper.inc
> +  }
Fixed

2021-11-15 11:29 UTC, cableman approved these changes

2021-11-15 13:02 UTC, merged